version: "3"

services:
  api:
    build: ../src/Crayons.Api
    ports:
      - 5000:5000
    networks:
      - crayons-net

  mssql:
    image: microsoft/mssql-server-linux
    ports:
      - 1433:1433
    networks:
      - crayons-net
    environment:
      SA_PASSWORD: "Crayons123!."
      ACCEPT_EULA: "Y"

networks: 
  crayons-net:
    driver: bridge